services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./index.html:/srv/index.html:ro
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    environment:
      - ACME_AGREE=true
    command: |
      caddy run --config /etc/caddy/Caddyfile

volumes:
  caddy_data:
  caddy_config: